# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

# Fixtures service
  TaskFixtures:
    class: AppBundle\DataFixtures\TaskFixtures
    tags: [doctrine.fixture.orm]

  UserFixtures:
    class: AppBundle\DataFixtures\UserFixtures
    tags: [ doctrine.fixture.orm ]

